name: Email Notification

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    types: [opened, closed]
  pull_request_review:
    types: [submitted]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Send Email Notification
      env:
        SMTP_SERVER: ${{ smtp.gmail.com }}
        SMTP_PORT: ${{ 587 }}
        SMTP_USERNAME: ${{ puneetjoshi412@gmail.com }}
        SMTP_PASSWORD: ${{ ++++++++ }}
        TO_EMAIL: "Puneetjoshi412@gmail.com"  # Replace with your email
        FROM_EMAIL: "Puneetjoshi412@gmail.com"  # Replace with your GitHub email
        SUBJECT: "GitHub Notification"
        BODY: |
          A GitHub event has occurred:
          - Event Type: ${{ github.event_name }}
          - Repository: ${{ github.repository }}
          - Action: ${{ github.event.action }}
          - Sender: ${{ github.actor }}
          - Branch: ${{ github.ref }}

      run: |
        echo -e "$BODY" | mailx -s "$SUBJECT" -S smtp-use-starttls -S smtp-auth=login -S smtp=$SMTP_SERVER:$SMTP_PORT -S from="$FROM_EMAIL" -S smtp-auth-user="$SMTP_USERNAME" -S smtp-auth-password="$SMTP_PASSWORD" "$TO_EMAIL"
