name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  send-email-notification:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # Ensure email notification runs even if the build job fails

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.USERNAME }}
          password: "scmriijkbicmzieq"
          from: "Your Name <your-email@gmail.com>"
          to: "anil.digitaldesign@gmail.com"
          subject: "GitHub Action Notification"
          body: "Hello from GitHub Actions! Your workflow has been triggered."
          content_type: text/plain
