name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main  # Adjust to your main branch name

jobs:
  send-email-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ Puneetjoshi412@gmail.com }}
          password: ${{ scmr iijk bicm zieq }}
          subject: "GitHub Notification"
          to: "anil.digitaldesign@gmail.com"  # Update with your Gmail email address
          body: |
            The repository has been updated.
            Event Type: ${{ github.event_name }}
            Repository: ${{ github.repository }}
            Action: ${{ github.event.action }}
            Sender: ${{ github.actor }}
            Branch: ${{ github.ref }}
